use std::fmt::Debug;

/// Represents the high-level events generated by UI components
/// that are then sent to the application's game loop over the MPSC channel.
#[derive(Debug, Clone)]
pub enum UIEvent {
    // --- Button & Interaction Events ---
    /// A button identified by its unique ID was clicked.
    /// The string holds the component's unique name (e.g., "start_game_btn").
    ButtonClicked(String),

    /// A button identified by its ID was toggled (e.g., a checkbox or a toggle switch).
    /// The string is the ID, and the boolean is the new state (true for ON).
    ButtonToggled(String, bool),

    // --- Input Events ---
    /// Text input was completed in a text field (usually via Enter key or loss of focus).
    /// The first string is the component's ID, and the second is the final submitted text.
    TextSubmitted(String, String),

    /// A slider or scrollbar value has changed.
    /// The string is the ID, and the f32 is the new normalized value (e.g., 0.0 to 1.0).
    ValueChanged(String, f32),

    // --- Window/System Events ---
    /// The UI requests that the application/game should immediately exit.
    ExitRequested,
}

#[derive(Debug, Clone)]
pub enum ComponentUpdate {
    SetText(String, String),          // (Component ID, New Text)
    SetValue(String, f32),            // (Component ID, New Value)
    SetLayerVisibility(String, bool), // (Layer ID, Is Visible)
}

#[derive(Debug, Clone)]
pub struct UIStateSnapshot {
    pub updates: Vec<ComponentUpdate>,
}
