use std::fmt::Debug;

// --- Abstract Key Code ---
#[derive(Debug, Clone, PartialEq)]
pub enum Key {
    // Alphanumeric keys (A-Z)
    A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
    
    // Numbers (0-9)
    Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key0,
    
    // Punctuation and Symbols (Simplified)
    Space, Return, Tab, Escape, Delete, Backspace,
    Semicolon, Equal, Comma, Minus, Period, Slash, Apostrophe, LBracket, RBracket, Grave,
    
    // Modifiers and Control
    LShift, RShift, LControl, RControl, LAlt, RAlt,
    
    // Arrows and Navigation
    Up, Down, Left, Right, Home, End, PageUp, PageDown, Insert,
    
    // Function Keys
    F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
    
    // Numpad Keys (Numpad0 to Numpad9)
    Numpad0, Numpad1, Numpad2, Numpad3, Numpad4, Numpad5, Numpad6, Numpad7, Numpad8, Numpad9,
    NumpadAdd, NumpadSubtract, NumpadMultiply, NumpadDivide, NumpadDecimal,
    
    // Fallback for unhandled keys
    Unknown,
}

#[derive(Debug, Clone, PartialEq)]
pub enum MouseButton {
    Left,
    Right,
    Middle,
    Other(u16),
}

#[derive(Debug, Clone, PartialEq)]
pub enum ElementState {
    Pressed,
    Released,
}

// --- The Input Contract (Consumed by UIManager) ---

#[derive(Debug, Clone)]
pub enum UIInputEvent {
    /// Tracks mouse position changes for hit-testing and hover states.
    /// Coordinates are in physical screen pixels (f32).
    CursorMoved { x: f32, y: f32 },

    /// Registers a mouse button press or release.
    MouseButton {
        button: MouseButton,
        state: ElementState,
        x: f32,
        y: f32,
    },

    /// Text input for text fields (e.g., 'a', 'b', 'c', but not control keys).
    ReceivedCharacter(char),

    /// A key press or release, useful for navigation, shortcuts, or text field control.
    KeyboardInput {
        state: ElementState,
        key: Key,
    },

    /// Scroll events for scrolling containers (normalized to pixels or lines).
    MouseWheel { delta_x: f32, delta_y: f32 },

    /// Notifies the UI of window resizing, triggering layout recalculation.
    /// The UIManager uses this to adjust proportional component bounds.
    WindowResized { width: u32, height: u32 },
}

/// Represents the high-level events generated by UI components
/// that are then sent to the application's game loop over the MPSC channel.
#[derive(Debug, Clone)]
pub enum UIEvent {
    ButtonClicked(String),
    ButtonToggled(String, bool),
    TextSubmitted(String, String),
    ValueChanged(String, f32),
    ExitRequested,
}

#[derive(Debug, Clone)]
pub enum ComponentUpdate {
    SetText(String, String),            // (Component ID, New Text)
    SetValue(String, f32),              // (Component ID, New Value)
    SetLayerVisibility(String, bool),   // (Layer ID, Is Visible)
    SetPosition(String, f64, f64),      // (Component ID, New X, New Y)
    Resize {width: f64, height: f64}
}

impl ComponentUpdate {
    /// Returns the target component ID if the update is for a component, otherwise None.
    pub fn get_target_id(&self) -> Option<&str> {
        match self {
            // These variants target a specific component ID
            ComponentUpdate::SetText(id, _) |
            ComponentUpdate::SetValue(id, _) |
            ComponentUpdate::SetPosition(id, _, _) => Some(id),
            
            // These variants target layers or are global, and should be handled separately
           ComponentUpdate::SetLayerVisibility(_, _) |
            ComponentUpdate::Resize { .. } => None,
        }
    }
    
    /// Returns the target layer ID if the update is for a layer, otherwise None.
    pub fn get_layer_id(&self) -> Option<&str> {
        match self {
            ComponentUpdate::SetLayerVisibility(id, _) => Some(id),
            _ => None,
        }
    }
}

/// A snapshot of the UI state changes that need to be applied.
#[derive(Debug, Clone)]
pub struct UIStateSnapshot {
    pub updates: Vec<ComponentUpdate>,
}