use std::error::Error;
use std::time::Instant;
use winit::application::ApplicationHandler;
use winit::event_loop::{ActiveEventLoop, EventLoop};
use winit::window::WindowId;

// --- Imports from fps_ui library ---
use fps_ui::{
    AppDriver, Color, UIEvent, UIMainContext, WindowEvent,
    components::panel::{Panel, RenderSource},
    components::{Button, FpsComponent, Label, TextInput},
    events::ComponentUpdate,
    geometry::Rect,
    layout::{AnchorPoint, LayoutMetrics, LengthMode},
    manager::Layer,
    manager::UIManager,
};

const WINDOW_WIDTH: u32 = 1600;
const WINDOW_HEIGHT: u32 = 900;

const LOGICAL_WIDTH: u32 = 800;
const LOGICAL_HEIGHT: u32 = 450;

/// The central application struct that holds the necessary state.
struct App {
    driver: Option<AppDriver<'static>>,
    manager: UIManager,

    last_fps_update: Instant,
    frame_count: u32,
    current_fps: u32,
}

// --------------------------------------------------------------------------
// This block implements the Winit behavior.
// --------------------------------------------------------------------------
impl ApplicationHandler for App {
    /// Initializes the window and the AppDriver (Renderer).
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        println!("--- Initializing Window and UI Renderer ---");

        match AppDriver::new(event_loop, LOGICAL_WIDTH, LOGICAL_HEIGHT, WINDOW_WIDTH, WINDOW_HEIGHT) {
            Ok(driver) => {
                self.driver = Some(driver);
            }
            Err(e) => {
                eprintln!("FATAL: Failed to initialize AppDriver/Pixels: {}", e);
                event_loop.exit();
            }
        }
    }

    /// Handles window events (Input and Redraw).
    fn window_event(&mut self, event_loop: &ActiveEventLoop, _id: WindowId, event: WindowEvent) {
        let driver = match self.driver.as_mut() {
            Some(d) => d,
            None => return,
        };

        self.manager.update_components();
        let ui_events = self.manager.process_input(&event, driver.logical_cursor());
        let mut update_username_label = |clear_input: bool| {
            let mut updates = Vec::new();

            let username_text =
                if let Some(comp) = self.manager.find_component_by_id_mut("username_input") {
                    // Now call the immutable trait method
                    comp.get_text().to_string()
                } else {
                    "ERROR: Input component not found".to_string()
                };

            // 2. Prepare the update for the username label
            let new_label_text = format!("Current Username: {}", username_text);
            let label_update =
                ComponentUpdate::SetText("username_label".to_string(), new_label_text);
            updates.push(label_update);

            // 3. Optional: Clear the input text and update the button
            if clear_input {
                let clear_update =
                    ComponentUpdate::SetText("username_input".to_string(), String::new());
                updates.push(clear_update);

                // Give visual feedback on the button
                let button_update = ComponentUpdate::SetText(
                    "connect_button".to_string(),
                    "CONNECTED!".to_string(),
                );
                updates.push(button_update);
            }

            // 4. Apply all collected updates
            self.manager.apply_updates(updates);
        };

        // Handle application-level UI events generated by components (e.g., TextSubmitted)
        for ui_event in ui_events {
            println!("UI Event received: {:?}", ui_event);

            match ui_event {
                UIEvent::TextSubmitted(id, text) => {
                    println!("Text submitted from ID '{}': \"{}\"", id, text);

                    if id == "username_input" {
                        // Action: Update label and clear input/button text
                        update_username_label(true);
                    }
                }
                UIEvent::ButtonClicked(id) => {
                    println!("Button clicked with ID: {}", id);

                    if id == "connect_button" {
                        // Action: Update label and clear input/button text
                        update_username_label(true);
                    }
                }
                _ => {}
            }
        }

        driver.handle_winit_event(&event);

        match event {
            WindowEvent::CloseRequested => {
                event_loop.exit();
            }
            WindowEvent::RedrawRequested => {
                // 1. FPS Calculation and Update
                let now = Instant::now();
                self.frame_count += 1;

                // Update the FPS counter approximately once per second
                if now.duration_since(self.last_fps_update).as_secs_f32() >= 1.0 {
                    let duration = now.duration_since(self.last_fps_update).as_secs_f32();
                    let fps = (self.frame_count as f32 / duration).round() as u32;

                    self.current_fps = fps;
                    self.last_fps_update = now;
                    self.frame_count = 0;

                    // --- Send Update to UIManager ---
                    let fps_update = ComponentUpdate::SetValue(
                        "fps_counter".to_string(), // Target ID of the FpsComponent
                        self.current_fps as f32,
                    );

                    // Construct the Vec<ComponentUpdate> and call the UIManager method
                    let updates = vec![fps_update];
                    self.manager.apply_updates(updates);
                }

                // 2. Render the UI
                if let Err(e) = driver.render(&mut self.manager) {
                    eprintln!("Pixels error during render: {:?}", e);
                    event_loop.exit();
                }
            }
            _ => (),
        }
    }

    /// Requests continuous redraws.
    fn about_to_wait(&mut self, _event_loop: &ActiveEventLoop) {
        if let Some(driver) = self.driver.as_ref() {
            driver.window().request_redraw();
        }
    }
}
// --------------------------------------------------------------------------

// --- Main Entry Point ---
fn main() -> Result<(), Box<dyn Error>> {
    println!("--- Starting fps_ui Test Harness ---");

    let event_loop = EventLoop::new()?;
    let ui_context = UIMainContext::new(
        //<----- main.rs(194, 9): binding `ui_context` declared here
        "assets/fonts/Symtext.ttf",
        LOGICAL_WIDTH as f64,
        LOGICAL_HEIGHT as f64,
    )?;
    let mut ui_manager = UIManager::new(ui_context); //<----- `ui_context` does not live long enough
    let full_bounds = Rect::new(0.0, 0.0, LOGICAL_WIDTH as f64, LOGICAL_HEIGHT as f64);

    let background_panel = Panel::new(
        "main_bg".to_string(),
        RenderSource::SolidColor(Color::RED),
        full_bounds,
    );

    let background_layer = Layer {
        id: "background".to_string(),
        z_index: 0,
        is_visible: true,
        is_modal: false,
        components: vec![Box::new(background_panel)],
    };

    ui_manager
        .add_layer(background_layer)
        .expect("Failed to add background layer.");

    // --- 2. Foreground Layer with Label ---

    // Define title label
    let label_bounds = Rect::new(0.11, 0.115, 1.0, 1.0);
    let title_label = Label::new(
        "title".to_string(),
        "aMAZE".to_string(),            // Initial text
        180.0,                          // Font size in virtual pixels
        Color::new(255, 255, 255, 255), // White color
        label_bounds,
        LayoutMetrics {
            anchor: AnchorPoint::TopLeft,
            positioning: LengthMode::Percent,
            sizing: LengthMode::Percent,
        },
    );
    let label2_bounds = Rect::new(0.115, 0.125, 1.0, 1.0); // x=20, y=20, max width=300, max height=50
    let title2_label = Label::new(
        "title2".to_string(),
        "aMAZE".to_string(),      // Initial text
        180.0,                    // Font size in virtual pixels
        Color::new(0, 0, 0, 255), // White color
        label2_bounds,
        LayoutMetrics {
            anchor: AnchorPoint::TopLeft,
            positioning: LengthMode::Percent,
            sizing: LengthMode::Percent,
        },
    );

    let text_input_bounds = Rect::new(0.11, 0.6, 400.0, 40.0);
    let text_input = TextInput::new(
        "username_input".to_string(),
        text_input_bounds,
        LayoutMetrics {
            anchor: AnchorPoint::TopLeft,
            positioning: LengthMode::Percent,
            sizing: LengthMode::Px,
        },
        "Enter username....".to_string(),
        16,
        30.0,
        Color::WHITE,
        Color::DARK_GRAY,
    );

    let username_label_bounds = Rect::new(0.11, 0.55, 400.0, 10.0);
    let username_label = Label::new(
        "username_label".to_string(),
        "set username here".to_string(),
        24.0,
        Color::WHITE,
        username_label_bounds,
        LayoutMetrics {
            anchor: AnchorPoint::TopLeft,
            positioning: LengthMode::Percent,
            sizing: LengthMode::Px,
        },
    );

    // Position it slightly below the text input, centered with it.
    let button_bounds = Rect::new(0.11, 0.7, 160.0, 40.0);
    let connect_button = Button::new(
        "connect_button", // ID to check for in UIEvent::Clicked
        "CONNECT",        // Button text
        button_bounds,
        LayoutMetrics {
            anchor: AnchorPoint::TopLeft,
            positioning: LengthMode::Percent,
            sizing: LengthMode::Px,
        },
        Color::WHITE,
        Color::BLACK,
        Color::DARK_GRAY,
    );

    // FpsComponent
    let fps_bounds = Rect::new(2.0, 2.0, 50.0, 24.0);
    let fps_component = FpsComponent::new(
        "fps_counter".to_string(),    // Crucial ID for updates
        24.0,                         // Font size
        Color::new(255, 255, 0, 255), // Yellow color
        fps_bounds,
        LayoutMetrics {
            anchor: AnchorPoint::TopLeft,
            positioning: LengthMode::Px,
            sizing: LengthMode::Px,
        },
    );

    let foreground_layer = Layer {
        id: "foreground".to_string(),
        z_index: 10,
        is_visible: true,
        is_modal: false,
        components: vec![
            Box::new(title2_label),
            Box::new(title_label),
            Box::new(text_input),
            Box::new(connect_button),
            Box::new(username_label),
            Box::new(fps_component),
        ],
    };

    ui_manager
        .add_layer(foreground_layer)
        .expect("Failed to add foreground layer.");

    // --- 3. App Initialization and Run (Unchanged) ---
    let now = Instant::now();
    let mut app: App = App {
        driver: None,
        manager: ui_manager,

        // --- FPS Tracking Initialization ---
        last_fps_update: now, // Initialize the timer start
        frame_count: 0,       // Initialize frame count
        current_fps: 0,       // Initialize displayed FPS
    };

    // Run the event loop
    event_loop.run_app(&mut app)?;

    println!("--- fps_ui Test Harness Exited Successfully ---");
    Ok(())
}
